### ISSUE TITLE
[Channel Permissions v4.2.3] - Hover over channels to view their required permissions.

### ISSUE THREAD

**Issue by mysticentity** [Farcrada/DiscordPlugins#100]
### Describe the bug

I restarted my discord and betterdiscord was uninstalled. Reinstalled it, went to hover over the channels and instant crash every time when I have Channel Permissions v4.2.3 enabled. 

### Expected behavior

To have discord not crash when hovering over the individual channels when Channel Permissions v4.2.3 is not enabled.

### To reproduce

1. Enable Channel Permissions v4.2.3
2. Hover over channel list
3. Instant crash

### OS version

Windows 10 Home 64 bit, version: 20H2, OS Build: 19042.1526, Experience: Windows Feature Experience Pack 120.2212.4170.0

### Discord version

Stable 139460 (ea9eb84)

### BetterDiscord version

BetterDiscord 1.5.3-Hotfix

### Plugin version

v4.2.3

### Additional context

Log when error occurred: 

`Prettified stacktraces, stack:
 TypeError: channel.isVocal is not a function
    at useActiveThreads (betterdiscord://plugins/ChannelPermissions.plugin.js:213:16)
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:242:5)
    at betterdiscord://plugins/ChannelPermissions.plugin.js:431:6 
Component stack:
     at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:231:12)
    at <anonymous>:4:230088
    at div
    at v (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3502:562)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3633:470)
    at g (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3630:206)
    at AppLayer
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3640:859)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3432:450)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3496:540)
    at CategoryPopoutComponent (betterdiscord://plugins/ChannelPermissions.plugin.js:420:11)
    at li
    at A (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4796:134)
    at A (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4796:134)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at ul
    at div
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3749:189
    at t.FocusJumpSection (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2174:673)
    at t (https://discord.com/assets/3327ca454b4a18158f65.js:824:12)
    at m (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4043:696)
    at t (https://discord.com/assets/54e8c6da46111431b089.js:32:767)
    at E (https://discord.com/assets/d23e602d059617a9289d.js:13:729)
    at https://discord.com/assets/d23e602d059617a9289d.js:10:944
    at Oe (https://discord.com/assets/3327ca454b4a18158f65.js:838:862)
    at Me (https://discord.com/assets/3327ca454b4a18158f65.js:840:886)
    at nav
    at t (https://discord.com/assets/5bf7954a257164664f51.js:1495:177)
    at Ge (https://discord.com/assets/5bf7954a257164664f51.js:1506:57)
    at https://discord.com/assets/5bf7954a257164664f51.js:42:734
    at div
    at Be (https://discord.com/assets/5bf7954a257164664f51.js:44:761)
    at div
    at div
    at div
    at t.default (https://discord.com/assets/5bf7954a257164664f51.js:35:22)
    at div
    at l (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4715:10)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:144:908)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4616:243)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:147:455)
    at Y (https://discord.com/assets/5bf7954a257164664f51.js:149:69)
    at div
    at t (https://discord.com/assets/5bf7954a257164664f51.js:310:360)
    at j (https://discord.com/assets/5bf7954a257164664f51.js:127:188)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6114:926)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6117:10)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:229:369)
    at Suspense
    at d
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6114:926)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6117:10)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3629:407)
    at VerificationLayerProvider
    at E (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2500:546)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3629:407)
    at AppLayerProvider
    at div
    at div
    at E (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:1937:9)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:697:893)
    at T (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:701:397)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:701:868)
    at u (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4264:151)
    at m (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:682:23)
    at re (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:685:453)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:743:63)
    at u (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4263:85)
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4780:30
    at H (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5928:700)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6111:570)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6067:817)
    at f (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2547:764)
(anonymous) @ 6e374320a6e33352f941.js:130
36e374320a6e33352f941.js:130 [ShowHiddenChannels] (v3.2.4) Fatal Error: "before" callback of render in Channels TypeError: x.record.isVocal is not a function
(anonymous) @ 6e374320a6e33352f941.js:130
/api/v9/guilds/212324635356692500/entitlements?with_sku=true&with_application=true&exclude_deleted=false:1 Failed to load resource: the server responded with a status of 403 ()`

**Comment by KingTeox** [comment]
@Farcrada -> #101
