### ISSUE TITLE
[Channel Permissions] Crash on hover

### ISSUE THREAD

**Issue by RobinRMC** [Farcrada/DiscordPlugins#66]
### Describe the bug

On some channels, the plugin let's your Discord client crash when you hover over it.

### Expected behavior

Not letting the Discord client crash.

### To reproduce

Just hover your mouse pointer over some channels and maybe you'll find a channel that crashes the client.

I've found only 1 server that's affected by this bug, but I don't know if I'm allowed to share it here.

### Screenshots

No screenshots, but I do have a stack trace (from CrashRecovery):

```
Prettified stacktraces, stack:
 TypeError: Cannot read property 'colorString' of undefined
    at ChannelPermissions.getPermissionElements (betterdiscord://plugins/ChannelPermissions.plugin.js:423:24)
    at ChannelPermissions.ChannelTooltip (betterdiscord://plugins/ChannelPermissions.plugin.js:298:28)
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:189:10) 
Component stack:
     at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:179:12)
    at <anonymous>:4:156428
    at div
    at T (https://discord.com/assets/40541a437a059592a634.js:5162:767)
    at E (https://discord.com/assets/40541a437a059592a634.js:2930:171)
    at div
    at t (https://discord.com/assets/40541a437a059592a634.js:950:12)
    at I (https://discord.com/assets/40541a437a059592a634.js:1501:291)
    at AppLayer
    at t (https://discord.com/assets/40541a437a059592a634.js:821:343)
    at t (https://discord.com/assets/40541a437a059592a634.js:1847:85)
    at t (https://discord.com/assets/40541a437a059592a634.js:923:209)
    at div
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:5860:495)
    at O (https://discord.com/assets/40541a437a059592a634.js:5676:244)
    at O (https://discord.com/assets/40541a437a059592a634.js:5676:244)
    at P (https://discord.com/assets/17ca92c3910ef2b76a52.js:5863:185)
    at E (https://discord.com/assets/40541a437a059592a634.js:2930:171)
    at div
    at div
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1928:73
    at t.FocusJumpSection (https://discord.com/assets/40541a437a059592a634.js:2850:905)
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:5799:638)
    at p (https://discord.com/assets/40541a437a059592a634.js:3823:625)
    at ie (https://discord.com/assets/17ca92c3910ef2b76a52.js:5811:847)
    at nav
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:7205:348)
    at we (https://discord.com/assets/17ca92c3910ef2b76a52.js:7216:187)
    at https://discord.com/assets/17ca92c3910ef2b76a52.js:7174:872
    at div
    at De (https://discord.com/assets/17ca92c3910ef2b76a52.js:7176:759)
    at div
    at div
    at div
    at je (https://discord.com/assets/17ca92c3910ef2b76a52.js:7177:671)
    at div
    at n (https://discord.com/assets/40541a437a059592a634.js:4622:605)
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:8492:447)
    at div
    at t (https://discord.com/assets/40541a437a059592a634.js:1597:162)
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:8495:97)
    at x (https://discord.com/assets/17ca92c3910ef2b76a52.js:8496:670)
    at div
    at t (https://discord.com/assets/17ca92c3910ef2b76a52.js:8574:943)
    at k (https://discord.com/assets/17ca92c3910ef2b76a52.js:7158:336)
    at t (https://discord.com/assets/40541a437a059592a634.js:506:363)
    at t (https://discord.com/assets/40541a437a059592a634.js:508:549)
    at n (https://discord.com/assets/17ca92c3910ef2b76a52.js:715:260)
    at u (https://discord.com/assets/40541a437a059592a634.js:3942:679)
    at Suspense
    at d
    at t (https://discord.com/assets/40541a437a059592a634.js:506:363)
    at t (https://discord.com/assets/40541a437a059592a634.js:508:549)
    at div
    at A (https://discord.com/assets/40541a437a059592a634.js:1946:487)
    at t (https://discord.com/assets/40541a437a059592a634.js:1500:499)
    at VerificationLayerProvider
    at t (https://discord.com/assets/40541a437a059592a634.js:1500:499)
    at AppLayerProvider
    at E (https://discord.com/assets/40541a437a059592a634.js:2930:171)
    at t (https://discord.com/assets/40541a437a059592a634.js:3800:517)
    at m (https://discord.com/assets/40541a437a059592a634.js:3914:943)
    at t (https://discord.com/assets/40541a437a059592a634.js:3915:436)
    at u (https://discord.com/assets/40541a437a059592a634.js:3942:679)
    at Z (https://discord.com/assets/40541a437a059592a634.js:5449:616)
    at t (https://discord.com/assets/40541a437a059592a634.js:5819:536)
    at u (https://discord.com/assets/40541a437a059592a634.js:3941:609)
    at https://discord.com/assets/40541a437a059592a634.js:5733:735
    at Y (https://discord.com/assets/40541a437a059592a634.js:5910:808)
    at t (https://discord.com/assets/40541a437a059592a634.js:502:856)
    at t (https://discord.com/assets/40541a437a059592a634.js:1055:819)
    at f (https://discord.com/assets/40541a437a059592a634.js:5896:678)```

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

1.2.1

### Plugin version

v4.0.4

### Additional context

I'm not sure if another plugin is interfering with Channel Permissions, so that could also be the cause. I don't think so, but it's possible. :P

**Comment by Farcrada** [comment]
Noted, I'm investigating. Are there other plugins you run that influence users or channels?

**Comment by Farcrada** [comment]
Does this update/version fix your issues: https://github.com/Farcrada/DiscordPlugins/blob/CP-dev/Channel-Permissions/ChannelPermissions.plugin.js ?
