### ISSUE TITLE
[ChannelPermissions] Crash is occuring

### ISSUE THREAD

**Issue by werewolfboy13** [Farcrada/DiscordPlugins#94]
### Describe the bug

Random Crashes are occuring, crash recovery is spitting out the call stack. 

### Expected behavior

N/A

### To reproduce

Appears to be caused when you are hovering over channel names

### Screenshots

![image](https://user-images.githubusercontent.com/43587009/178073341-17e74c64-2baf-406d-ab1c-c0aa2bfff5d5.png)

### OS version

11

### Discord version

Canary

### BetterDiscord version

1.5.3

### Plugin version

4.2.1

### Additional context

```
c65b87c1282cfdba96da.js:130 [CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'role' of undefined
    at ChannelPermissions.createRoleElement (betterdiscord://plugins/ChannelPermissions.plugin.js:585:67)
    at ChannelPermissions.getPermissionElements (betterdiscord://plugins/ChannelPermissions.plugin.js:664:40)
    at ChannelPermissions.ChannelTooltipComponent (betterdiscord://plugins/ChannelPermissions.plugin.js:480:29)
    at betterdiscord://plugins/ChannelPermissions.plugin.js:324:18 
Component stack:
     at ChannelPermissions.ChannelTooltipComponent (betterdiscord://plugins/ChannelPermissions.plugin.js:478:11)
    at div
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:230:12)
    at <anonymous>:4:230112
    at div
    at v (https://canary.discord.com/assets/7404909db95f8f955250.js:3538:562)
    at T (https://canary.discord.com/assets/7404909db95f8f955250.js:2202:293)
    at div
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3669:470)
    at S (https://canary.discord.com/assets/7404909db95f8f955250.js:3666:206)
    at AppLayer
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3676:859)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3468:857)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3532:540)
    at li
    at t (https://canary.discord.com/assets/7592b2de7bf8efc0e9ac.js:873:176)
    at O (https://canary.discord.com/assets/7404909db95f8f955250.js:4806:134)
    at O (https://canary.discord.com/assets/7404909db95f8f955250.js:4806:134)
    at x (https://canary.discord.com/assets/7592b2de7bf8efc0e9ac.js:877:504)
    at T (https://canary.discord.com/assets/7404909db95f8f955250.js:2202:293)
    at ul
    at div
    at https://canary.discord.com/assets/7404909db95f8f955250.js:3788:189
    at t.FocusJumpSection (https://canary.discord.com/assets/7404909db95f8f955250.js:2187:105)
    at t (https://canary.discord.com/assets/7592b2de7bf8efc0e9ac.js:811:958)
    at h (https://canary.discord.com/assets/7404909db95f8f955250.js:4079:696)
    at t (https://canary.discord.com/assets/75d79eb10df0783d238f.js:32:907)
    at E (https://canary.discord.com/assets/b6d1111cb9b45c0e754c.js:13:49)
    at https://canary.discord.com/assets/b6d1111cb9b45c0e754c.js:10:345
    at be (https://canary.discord.com/assets/7592b2de7bf8efc0e9ac.js:826:834)
    at Ee (https://canary.discord.com/assets/7592b2de7bf8efc0e9ac.js:828:800)
    at nav
    at t (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:1440:177)
    at Be (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:1451:90)
    at https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:41:734
    at div
    at Be (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:43:761)
    at div
    at div
    at div
    at t.default (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:34:22)
    at div
    at l (https://canary.discord.com/assets/7404909db95f8f955250.js:4725:10)
    at t (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:142:915)
    at div
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:4626:564)
    at t (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:145:505)
    at Y (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:147:69)
    at div
    at t (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:306:360)
    at j (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:125:188)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6124:926)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6127:10)
    at t (https://canary.discord.com/assets/82854bb9bf81d1fe0e6c.js:227:369)
    at Suspense
    at d
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6124:926)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6127:10)
    at div
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3665:407)
    at VerificationLayerProvider
    at E (https://canary.discord.com/assets/7404909db95f8f955250.js:2510:293)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:3665:407)
    at AppLayerProvider
    at div
    at div
    at E (https://canary.discord.com/assets/7404909db95f8f955250.js:1945:481)
    at T (https://canary.discord.com/assets/7404909db95f8f955250.js:2202:293)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:745:655)
    at m (https://canary.discord.com/assets/7404909db95f8f955250.js:749:113)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:749:584)
    at u (https://canary.discord.com/assets/7404909db95f8f955250.js:4280:738)
    at h (https://canary.discord.com/assets/7404909db95f8f955250.js:729:572)
    at re (https://canary.discord.com/assets/7404909db95f8f955250.js:733:313)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:790:116)
    at u (https://canary.discord.com/assets/7404909db95f8f955250.js:4279:679)
    at https://canary.discord.com/assets/7404909db95f8f955250.js:4790:30
    at H (https://canary.discord.com/assets/7404909db95f8f955250.js:5938:700)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6121:570)
    at t (https://canary.discord.com/assets/7404909db95f8f955250.js:6077:817)
    at _ (https://canary.discord.com/assets/7404909db95f8f955250.js:2557:813)
```

**Comment by Farcrada** [comment]
Canary always likes poking holes in working structures.

Next update will fix, releasing now.

**Comment by Farcrada** [comment]
Worth noting that you're on Canary and that crashes should be expected.

Plugins (at least mine) are made for Stable; though this change seems to be working fine with stable. Some changes in Canary don't make it to Stable which then messes up the plugin even more.

**Comment by werewolfboy13** [comment]
Ahh gotcha.
