### ISSUE TITLE
[ChannelPermissions] Crashing after recent stable update

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Farcrada/DiscordPlugins#99]
### Describe the bug

After the recent update to PTB & Stable, simply hover over the channels causes discord to crash

### Expected behavior

to not crash?

### To reproduce

Just hover over a channel with this plugin enabled & discord crashes.

### Screenshots

<img width="1679" alt="Screen Shot 2022-08-02 at 7 35 25 am" src="https://user-images.githubusercontent.com/2242880/182250488-20c84f75-9bb9-409b-b937-e3d3e3e36e6b.png">

### OS version

macOS 11.6.7

### Discord version

Stable

### BetterDiscord version

BetterDiscord 1.5.3-Hotfix

### Plugin version

v4.2.3

### Additional context

Crash log:
```text
[2022-08-01 21:15:35.115][CONSOLE:ERROR] channel.isVocal is not a function
TypeError: channel.isVocal is not a function
    at useActiveThreads (betterdiscord://plugins/ChannelPermissions.plugin.js:213:16)
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:242:5)
    at so (https://discord.com/assets/e5880ab2ccec6da98ca7.js:5994:468)
    at $s (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6046:48)
    at Gu (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6037:748)
    at wu (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6037:676)
    at Uu (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6037:539)
    at Au (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6034:164)
    at https://discord.com/assets/e5880ab2ccec6da98ca7.js:5979:340
    at t.unstable_runWithPriority (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6168:828)
    at Ki (https://discord.com/assets/e5880ab2ccec6da98ca7.js:5979:117)
    at qi (https://discord.com/assets/e5880ab2ccec6da98ca7.js:5979:285)
    at Xi (https://discord.com/assets/e5880ab2ccec6da98ca7.js:5979:220)
    at Tu (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6031:510)
    at Object.enqueueSetState (https://discord.com/assets/e5880ab2ccec6da98ca7.js:5983:240)
    at t.h.setState (https://discord.com/assets/e5880ab2ccec6da98ca7.js:6138:297)
    at betterdiscord://plugins/ChannelPermissions.plugin.js:325:18
    at r (https://discord.com/assets/3e442983608b8c3b4154.js:126:559)
```

**Comment by Bigglesworth43** [comment]
Im having the same issue on Windows 10. Narrowed it down to this plugin by disabling all other plugins and re-enabling one at a time till I recreated the crash. Happens every time I hover over a channel.

**Comment by teisseire117** [comment]
I have same issue.

@Bigglesworth43 Next time don't bother doing that, enable the debug.log and when a crash happens open the file and you'll see what plug-in caused it

**Comment by Bigglesworth43** [comment]
I see, thanks that woulda saved me a lot of time.

**Comment by mysticentity** [comment]
Just got this too. I restarted my discord and betterdiscord was uninstalled. Reinstalled it, went to hover over the channels and instant crash every time. 

OS version:
Windows 10 Home 64 bit, version: 20H2, OS Build: 19042.1526, Experience: Windows Feature Experience Pack 120.2212.4170.0

Stable 139460 (ea9eb84)
BetterDiscord 1.5.3-Hotfix

Plugin version
v4.2.3

Crash log:


`Prettified stacktraces, stack:
 TypeError: channel.isVocal is not a function
    at useActiveThreads (betterdiscord://plugins/ChannelPermissions.plugin.js:213:16)
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:242:5)
    at betterdiscord://plugins/ChannelPermissions.plugin.js:431:6 
Component stack:
     at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:231:12)
    at <anonymous>:4:230088
    at div
    at v (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3502:562)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3633:470)
    at g (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3630:206)
    at AppLayer
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3640:859)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3432:450)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3496:540)
    at CategoryPopoutComponent (betterdiscord://plugins/ChannelPermissions.plugin.js:420:11)
    at li
    at A (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4796:134)
    at A (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4796:134)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at ul
    at div
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3749:189
    at t.FocusJumpSection (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2174:673)
    at t (https://discord.com/assets/3327ca454b4a18158f65.js:824:12)
    at m (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4043:696)
    at t (https://discord.com/assets/54e8c6da46111431b089.js:32:767)
    at E (https://discord.com/assets/d23e602d059617a9289d.js:13:729)
    at https://discord.com/assets/d23e602d059617a9289d.js:10:944
    at Oe (https://discord.com/assets/3327ca454b4a18158f65.js:838:862)
    at Me (https://discord.com/assets/3327ca454b4a18158f65.js:840:886)
    at nav
    at t (https://discord.com/assets/5bf7954a257164664f51.js:1495:177)
    at Ge (https://discord.com/assets/5bf7954a257164664f51.js:1506:57)
    at https://discord.com/assets/5bf7954a257164664f51.js:42:734
    at div
    at Be (https://discord.com/assets/5bf7954a257164664f51.js:44:761)
    at div
    at div
    at div
    at t.default (https://discord.com/assets/5bf7954a257164664f51.js:35:22)
    at div
    at l (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4715:10)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:144:908)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4616:243)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:147:455)
    at Y (https://discord.com/assets/5bf7954a257164664f51.js:149:69)
    at div
    at t (https://discord.com/assets/5bf7954a257164664f51.js:310:360)
    at j (https://discord.com/assets/5bf7954a257164664f51.js:127:188)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6114:926)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6117:10)
    at t (https://discord.com/assets/5bf7954a257164664f51.js:229:369)
    at Suspense
    at d
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6114:926)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6117:10)
    at div
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3629:407)
    at VerificationLayerProvider
    at E (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2500:546)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:3629:407)
    at AppLayerProvider
    at div
    at div
    at E (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:1937:9)
    at h (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2190:9)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:697:893)
    at T (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:701:397)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:701:868)
    at u (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4264:151)
    at m (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:682:23)
    at re (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:685:453)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:743:63)
    at u (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4263:85)
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:4780:30
    at H (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5928:700)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6111:570)
    at t (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6067:817)
    at f (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:2547:764)
(anonymous) @ 6e374320a6e33352f941.js:130
36e374320a6e33352f941.js:130 [ShowHiddenChannels] (v3.2.4) Fatal Error: "before" callback of render in Channels TypeError: x.record.isVocal is not a function
(anonymous) @ 6e374320a6e33352f941.js:130
/api/v9/guilds/212324635356692500/entitlements?with_sku=true&with_application=true&exclude_deleted=false:1 Failed to load resource: the server responded with a status of 403 ()`

**Comment by KingTeox** [comment]
#101

**Comment by Farcrada** [comment]
Thank you all for your patience! Found some time to handle this, should be up soon.
